services:
    tee:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
            - tee:/app/telegram_account_session/
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - TELEGRAM_ACCOUNT_PHONE=${TELEGRAM_ACCOUNT_PHONE}
            - TELEGRAM_ACCOUNT_APP_ID=${TELEGRAM_ACCOUNT_APP_ID}
            - TELEGRAM_ACCOUNT_APP_HASH=${TELEGRAM_ACCOUNT_APP_HASH}
            - TELEGRAM_ACCOUNT_DEVICE_MODEL=${TELEGRAM_ACCOUNT_DEVICE_MODEL}
            - TELEGRAM_ACCOUNT_SYSTEM_VERSION=${TELEGRAM_ACCOUNT_SYSTEM_VERSION}
        ports:
            - "3123:3000"
        restart: always

volumes:
    tee:
