services:
    tee:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - type: bind
              source: agent/data/db.sqlite
              target: /app/agent/data/db.sqlite
            - type: bind
              source: agent/data/telegram_account_session/
              target: /app/agent/data/telegram_account_session/
            - type: bind
              source: .env
              target: /app/.env
        ports:
            - "3123:3000"
        restart: always

volumes:
    tee:
